version: "3.8"

services:
  icarus-auth-webserver:
    build:
      context: icarus-auth-webserver
      dockerfile: Dockerfile
    image: cricarusprod001.azurecr.io/icarus-dev:amd64-auth-webserver

  icarus-auth-storage:
    build:
      context: icarus-auth-storage
      dockerfile: Dockerfile
    image: cricarusprod001.azurecr.io/icarus-dev:amd64-auth-storage