version: "3.8"

services:
  icarus-auth-webserver:
    image: cricarusprod001.azurecr.io/icarus-auth-webserver
    container_name: icarus-auth-webserver
    ports:
      - 8000:8000
    environment:
      - PSQL_DB_NAME=${PSQL_DB_NAME}
      - PSQL_DB_USER=${PSQL_DB_USER}
      - PSQL_DB_PASSWORD=${PSQL_DB_PASSWORD}
      - PSQL_DB_HOST=icarus-auth-storage
    entrypoint: ["./scripts/start.dev.sh"]
    depends_on: 
      - icarus-auth-storage

  icarus-auth-storage:
    image: cricarusprod001.azurecr.io/icarus-auth-storage
    container_name: icarus-auth-storage
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${PSQL_DB_USER}
      - POSTGRES_PASSWORD=${PSQL_DB_PASSWORD}

  icarus-auth-proxy:
    image: cricarusprod001.azurecr.io/icarus-auth-proxy
    container_name: icarus-auth-proxy
    ports:
      - 800:80
    volumes:
      - ${CERTIFICATE_CERT_PATH}:/etc/ssl/certs/nginx.crt:ro
      - ${CERTIFICATE_KEY_PATH}:/etc/ssl/private/nginx.key:ro
    depends_on:
      - icarus-auth-webserver
